### ISSUE TITLE
greekToEnglish function optimization

### ISSUE THREAD

**Issue by MeNsaaH** [Go-phie/gophie-web#77]
https://github.com/Go-phie/gophie-web/blob/master/src/utils/index.js#L108 
The codeblock here can be optimized to use the regular `myMap.get(key)` instead of the for statement.

@SLKhadeeja You could look into this :)

**Comment by deven96** [comment]
greekToEnglish is supposed to get key from value not the other way around
-------- Original message --------From: Mmadu Manasseh <notifications@github.com> Date: 11/05/2020  10:05 pm  (GMT+01:00) To: Go-phie/gophie-web <gophie-web@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Go-phie/gophie-web] greekToEnglish function optimization (#77) 
https://github.com/Go-phie/gophie-web/blob/master/src/utils/index.js#L108
The codeblock here can be optimized to use the regular myMap.get(key) instead of the for statement.
@SLKhadeeja You could look into this :)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Go-phie/gophie-web/issues/77",
"url": "https://github.com/Go-phie/gophie-web/issues/77",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MeNsaaH** [comment]
What's the inspiration for that? Why not the other way round?

**Comment by deven96** [comment]
If you look at the movie object, it comes from gophie core with it's source in english... hence the function to convert it to greek and the map to convert greek to english... basically just to avoid writing names anywhere else except this file
-------- Original message --------From: Mmadu Manasseh <notifications@github.com> Date: 11/05/2020  11:06 pm  (GMT+01:00) To: Go-phie/gophie-web <gophie-web@noreply.github.com> Cc: Diretnan Domnan <diretnandomnan@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [Go-phie/gophie-web] greekToEnglish function optimization (#77) 
What's the inspiration for that? Why not the other way round?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Go-phie/gophie-web/issues/77#issuecomment-626991023",
"url": "https://github.com/Go-phie/gophie-web/issues/77#issuecomment-626991023",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MeNsaaH** [comment]
Okay
